"""The mode-distance confidence and the fitting/evaluation helpers."""

from __future__ import annotations

import numpy as np
import pytest
from hypothesis import given
from hypothesis import strategies as st

from jevemu.confidence import CONFIDENCE_FUNCTIONS, mode_distance, peak_linear, uniform_spread
from jevemu.confidence.fit import ConfidenceSample, evaluate, fit_power


@given(st.lists(st.floats(0.0, 1.0), min_size=2, max_size=12).filter(lambda v: sum(v) > 0))
def test_mode_distance_is_peak_linear_for_choice_answers(values: list[float]) -> None:
    probs = [v / sum(values) for v in values]
    assert mode_distance(probs) == pytest.approx(peak_linear(probs), abs=1e-12)


@pytest.mark.parametrize(
    ("probs", "reported"),
    [
        # docs.typesafe.ai ScoreExplorer widget answers where peak_linear misses (0.825, 0.36)
        pytest.param([0.0, 0.14, 0.86, 0.0, 0.0], 0.89, id="outfit_formality_K5"),
        pytest.param([0.0, 0.0, 0.48, 0.52], 0.52, id="candidate_fit_K4"),
        # Jev select answers (sst5)
        pytest.param([0.55, 0.45, 0.0, 0.0, 0.0], 0.63, id="sst5_two_levels"),
        pytest.param([0.09, 0.57, 0.03, 0.3, 0.01], 0.39, id="sst5_mass_two_levels_away"),
    ],
)
def test_mode_distance_reproduces_jev_score_confidence(probs: list[float], reported: float) -> None:
    # Each displayed probability is within 0.005 of Jev's, and so is the reported confidence.
    k, mode = len(probs), probs.index(max(probs))
    bound = 0.005 * sum(abs(i - mode) for i in range(k)) / uniform_spread(k, ordinal=True) + 0.005
    assert mode_distance(probs, ordinal=True) == pytest.approx(reported, abs=bound)


def test_score_confidence_charges_distant_mass_more() -> None:
    near = [0.0, 0.3, 0.7, 0.0, 0.0]
    far = [0.3, 0.0, 0.7, 0.0, 0.0]
    assert mode_distance(near, ordinal=True) > mode_distance(far, ordinal=True)
    assert mode_distance(near) == mode_distance(far)  # nominal: only p_max matters
    assert mode_distance([0.0, 0.0, 1.0, 0.0, 0.0], ordinal=True) == 1.0
    assert mode_distance([0.2] * 5, ordinal=False) == pytest.approx(0.0)


def samples_with_gamma(gamma: float, n: int, seed: int) -> list[ConfidenceSample]:
    rng = np.random.default_rng(seed)
    out = []
    for _ in range(n):
        kind = "score" if rng.uniform() < 0.5 else "choice"
        probs = tuple(rng.dirichlet(np.full(5, 0.5)).tolist())
        value = mode_distance(probs, ordinal=kind == "score") ** gamma
        out.append(ConfidenceSample("synthetic", kind, probs, round(value, 2)))
    return out


def test_power_fit_recovers_a_known_exponent() -> None:
    fitted = fit_power(samples_with_gamma(1.5, 2000, 0), "mode_distance")
    assert fitted.gammas["choice"] == pytest.approx(1.5, rel=0.02)
    assert fitted.gammas["score"] == pytest.approx(1.5, rel=0.02)


def test_evaluate_reports_rounded_errors_per_kind_and_k() -> None:
    samples = samples_with_gamma(1.0, 400, 1)
    rows = evaluate({"mode_distance": CONFIDENCE_FUNCTIONS["mode_distance"]}, samples)
    by_group = {(r.kind, r.k): r for r in rows}
    assert by_group[("all", None)].n == 400
    assert by_group[("all", None)].mae == 0.0  # generated by the same function, rounded alike
    assert by_group[("all", None)].exact == 1.0
    assert by_group[("choice", 5)].n + by_group[("score", 5)].n == 400
